import type { Metadata } from "next";
import "./globals.css";
import { ToastContainer, toast } from "react-toastify";
import 'react-toastify/dist/ReactToastify.css'
import Navbar from "./components/Navbar/Navbar";

export const metadata: Metadata = {
  title: "FitSphere_admin",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <Navbar/>
        {children}
        <ToastContainer/>
      </body>
    </html>
  );
}
